// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CryptosClient is the client API for Cryptos service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CryptosClient interface {
	// Geeting a crypto by id
	Get(ctx context.Context, in *CryptoId, opts ...grpc.CallOption) (*Crypto, error)
	GetAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Cryptos_GetAllClient, error)
	AddCrypto(ctx context.Context, in *Crypto, opts ...grpc.CallOption) (*CryptoId, error)
}

type cryptosClient struct {
	cc grpc.ClientConnInterface
}

func NewCryptosClient(cc grpc.ClientConnInterface) CryptosClient {
	return &cryptosClient{cc}
}

func (c *cryptosClient) Get(ctx context.Context, in *CryptoId, opts ...grpc.CallOption) (*Crypto, error) {
	out := new(Crypto)
	err := c.cc.Invoke(ctx, "/Crypto.Cryptos/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cryptosClient) GetAll(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (Cryptos_GetAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &Cryptos_ServiceDesc.Streams[0], "/Crypto.Cryptos/GetAll", opts...)
	if err != nil {
		return nil, err
	}
	x := &cryptosGetAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Cryptos_GetAllClient interface {
	Recv() (*Crypto, error)
	grpc.ClientStream
}

type cryptosGetAllClient struct {
	grpc.ClientStream
}

func (x *cryptosGetAllClient) Recv() (*Crypto, error) {
	m := new(Crypto)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cryptosClient) AddCrypto(ctx context.Context, in *Crypto, opts ...grpc.CallOption) (*CryptoId, error) {
	out := new(CryptoId)
	err := c.cc.Invoke(ctx, "/Crypto.Cryptos/AddCrypto", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CryptosServer is the server API for Cryptos service.
// All implementations must embed UnimplementedCryptosServer
// for forward compatibility
type CryptosServer interface {
	// Geeting a crypto by id
	Get(context.Context, *CryptoId) (*Crypto, error)
	GetAll(*empty.Empty, Cryptos_GetAllServer) error
	AddCrypto(context.Context, *Crypto) (*CryptoId, error)
	mustEmbedUnimplementedCryptosServer()
}

// UnimplementedCryptosServer must be embedded to have forward compatible implementations.
type UnimplementedCryptosServer struct {
}

func (UnimplementedCryptosServer) Get(context.Context, *CryptoId) (*Crypto, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedCryptosServer) GetAll(*empty.Empty, Cryptos_GetAllServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedCryptosServer) AddCrypto(context.Context, *Crypto) (*CryptoId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCrypto not implemented")
}
func (UnimplementedCryptosServer) mustEmbedUnimplementedCryptosServer() {}

// UnsafeCryptosServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CryptosServer will
// result in compilation errors.
type UnsafeCryptosServer interface {
	mustEmbedUnimplementedCryptosServer()
}

func RegisterCryptosServer(s grpc.ServiceRegistrar, srv CryptosServer) {
	s.RegisterService(&Cryptos_ServiceDesc, srv)
}

func _Cryptos_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CryptoId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptosServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Crypto.Cryptos/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptosServer).Get(ctx, req.(*CryptoId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cryptos_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CryptosServer).GetAll(m, &cryptosGetAllServer{stream})
}

type Cryptos_GetAllServer interface {
	Send(*Crypto) error
	grpc.ServerStream
}

type cryptosGetAllServer struct {
	grpc.ServerStream
}

func (x *cryptosGetAllServer) Send(m *Crypto) error {
	return x.ServerStream.SendMsg(m)
}

func _Cryptos_AddCrypto_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Crypto)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CryptosServer).AddCrypto(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Crypto.Cryptos/AddCrypto",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CryptosServer).AddCrypto(ctx, req.(*Crypto))
	}
	return interceptor(ctx, in, info, handler)
}

// Cryptos_ServiceDesc is the grpc.ServiceDesc for Cryptos service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cryptos_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Crypto.Cryptos",
	HandlerType: (*CryptosServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Cryptos_Get_Handler,
		},
		{
			MethodName: "AddCrypto",
			Handler:    _Cryptos_AddCrypto_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAll",
			Handler:       _Cryptos_GetAll_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/crypto.proto",
}
